# render.yaml (Versión FINAL PRODUCCIÓN - Conexión Exitosa)

envVarGroups:
  - name: secrets
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false

databases:
  - name: asistente-legal-db
    databaseName: asistente_legal_db
    user: asistente_legal_user
    plan: free

services:
  # 1. Backend (Cerebro)
  - name: asistente-legal-backend
    type: web
    runtime: python
    # El build solo instala librerías
    buildCommand: "pip install -r requirements.txt"
    
    # La lógica de IA y BD va al arranque
    startCommand: |
      rm -rf backend/archivos_subidos/*
      rm -rf chroma_db_data
      python -m backend.scripts.ingestar_documentos
      python -m backend.seed_db
      uvicorn backend.main:aplicacion --host 0.0.0.0 --port $PORT
      
    healthCheckPath: /
    plan: free
    envVars:
      - fromGroup: secrets
      - key: DATABASE_URL
        fromDatabase:
          name: asistente-legal-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.5
      # CONFIGURACIÓN DE SEGURIDAD: Solo tu Frontend real puede hablar con el Backend
      - key: CORS_ORIGINS
        value: "https://asistente-legal-frontend-897g.onrender.com,http://localhost:5173"

  # 2. Frontend (Rostro)
  - name: asistente-legal-frontend
    type: web
    runtime: static
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # CONEXIÓN NEURONAL: Aquí le decimos al Frontend dónde está su Backend real
      - key: VITE_URL_BASE_BACKEND
        value: "https://asistente-legal-backend-897g.onrender.com"